! conversion between
!    COMMAND_ARGUMENT_COUNT and IARGC
!    GET_COMMAND_ARGUMENT and GETARG

  FUNCTION COMMAND_ARGUMENT_COUNT()
    INTEGER :: COMMAND_ARGUMENT_COUNT
    COMMAND_ARGUMENT_COUNT=IARGC()
    RETURN
  END FUNCTION

  SUBROUTINE GET_COMMAND_ARGUMENT(m,p)
    CHARACTER(LEN=128) :: p
    INTEGER :: m
    CALL GETARG(m,p)
  END SUBROUTINE
